spring.datasource.url=jdbc:postgresql://localhost:5432/DATN
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
jwt.secret=mysecretkeymysecretkeymysecretkey123456
jwt.expiration=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
